In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('C:\\Users\\zzuge\\df.csv',encoding='cp949')

In [4]:
df

,geometry,NODE_ID,NODE_TYPE,TURN_P,REMARK
0,"Shapefile.Point(306862.5290999946, 364128.7581...",3680002100,101,0,NaN
1,"Shapefile.Point(232175.56361976278, 428286.284...",1865949201,101,0,NaN
2,"Shapefile.Point(262099.2841216855, 260200.9640...",3280218301,101,0,교차로명없음
3,"Shapefile.Point(261776.79685912761, 260206.480...",3280218201,101,1,교차로명없음
4,"Shapefile.Point(261777.6434585629, 259856.5594...",3280218101,101,1,NaN
...,...,...,...,...,...
200897,"Shapefile.Point(276681.37419968727, 311730.005...",3950099001,101,0,NaN
200898,"Shapefile.Point(277172.98334151093, 313481.357...",3950099401,104,0,NaN
200899,"Shapefile.Point(277185.10680105817, 313574.621...",3950099501,101,0,NaN
200900,"Shapefile.Point(277198.45956309163, 313675.035...",3950099601,101,0,NaN
200901,"Shapefile.Point(276486.0488271522, 313162.5098...",3950099301,101,0,NaN

In [5]:
import matplotlib.pyplot as plt

In [6]:
!pip install pyshp
!pip install pyproj

Requirement already satisfied: pyshp in c:\users\zzuge\anaconda3\lib\site-packages (2.3.1)
Requirement already satisfied: pyproj in c:\users\zzuge\anaconda3\lib\site-packages (3.4.0)
Requirement already satisfied: certifi in c:\users\zzuge\anaconda3\lib\site-packages (from pyproj) (2021.10.8)

In [7]:
import shapefile  #the pyshp module : Should install pyshp module.
import pandas as pd
from pyproj import Proj, transform  #Should install pyproj module.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200902 entries, 0 to 200901
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   geometry   200902 non-null  object
 1   NODE_ID    200902 non-null  int64
 2   NODE_TYPE  200902 non-null  int64
 3   NODE_NAME  200898 non-null  object
 4   TURN_P     200868 non-null  float64
 5   REMARK     3077 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 9.2+ MB

In [12]:
inProj = Proj(init = 'epsg:5186')
outProj= Proj(init = 'epsg:4326')
latitude = []
longitude= []
for idx,row in df.iterrows():
    x,y  = row.geometry[0][0],row.geometry[0][1]  # korea 2000 좌표계
    nx,ny = transform(inProj,outProj,x,y)     # 새로운 좌표계    
    latitude.append(ny)
    longitude.append(nx)
df['latitude'] = latitude
df['longitude']= longitude
del df['geometry'] # delete coords

C:\Users\zzuge\Anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\zzuge\Anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

IndexError: string index out of range

In [8]:
shp_path_node = 'C:\\Users\\zzuge\\git\\bigcon2x\\bigcon22\\EC\\01_data\\표준노드링크/MOCT_NODE.shp'
sf_node = shapefile.Reader(shp_path_node,encoding='cp949')
shp_path_link = 'C:\\Users\\zzuge\\git\\bigcon2x\\bigcon22\\EC\\01_data\\표준노드링크/MOCT_LINK.shp'
sf_link = shapefile.Reader(shp_path_link,encoding='cp949')

In [20]:
# construct pandas dataframe

#grab the shapefile's field names
# node
fields_node = [x[0] for x in sf_node.fields][1:]
records_node = sf_node.records()
shps = [s.points for s in sf_node.shapes()] # node has coordinate data.
# link
fields_link = [x[0] for x in sf_link.fields][1:]
records_link = sf_link.records()


#write the records into a dataframe
# node
node_dataframe = pd.DataFrame(columns=fields_node, data=records_node)
#add the coordinate data to a column called "coords"
node_dataframe = node_dataframe.assign(coords=shps)
# link
link_dataframe = pd.DataFrame(columns=fields_link, data=records_link)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte

In [9]:
fields_link = [x[0] for x in sf_link.fields][1:]
records_link = sf_link.records()

In [10]:
link_dataframe = pd.DataFrame(columns=fields_link, data=records_link)

In [11]:
link_dataframe

,LINK_ID,F_NODE,T_NODE,LANES,ROAD_RANK,ROAD_TYPE,ROAD_NO,ROAD_NAME,ROAD_USE,MULTI_LINK,CONNECT,MAX_SPD,REST_VEH,REST_W,REST_H,LENGTH,REMARK
0,1860689001,1865963801,1865963701,2,107,000,-,국제과학로,0,0,000,30,0,0,0,414.856758,
1,1860688901,1865963701,1865963801,2,107,000,-,국제과학로,0,0,000,30,0,0,0,414.211972,
2,3280619601,3280218301,3280218501,2,107,003,-,-,0,0,000,30,0,0,0,102.163661,도로명없음
3,3280619701,3280218501,3280218301,2,107,003,-,-,0,0,000,30,0,0,0,102.036940,도로명없음
4,3280618801,3280218201,3280218101,2,107,000,-,-,0,0,000,30,0,0,0,347.266337,도로명없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540320,3950263601,3950099601,3950099501,1,103,000,59,,0,0,000,60,0,0,0,100.984730,
540321,3950263901,3950007601,3950099601,2,103,000,59,친환경로,0,0,000,60,0,0,0,253.587305,
540322,3950263801,3950099601,3950007601,1,103,000,59,친환경로,0,0,000,60,0,0,0,255.217243,
540323,3950263201,3950099601,3950099301,1,107,000,,친환경로,0,0,000,60,0,0,0,901.044178,
540324,3950263301,3950099301,3950099601,1,107,000,,친환경로,0,0,000,60,0,0,0,894.603069,

In [12]:
link_dataframe.to_csv('C:\\Users\\zzuge\\link_dataframe.csv')